### PR TITLE
Add Maven vs Gradle section to README

### PR DESCRIPTION
**Pull request by proubatsis**
Add a paragraph discussing the differences between Maven and Gradle #35

### CODE REVIEW

**Comment by evelinec** [comment]
We would like to see how this section looks in the flow of the guide. @proubatsis if you can produce a rendered guide, let's review it.

**Comment by yeekangc** [comment]
Yes, we should not merge until it has been reviewed and we have consensus that this should be done.

**Comment by evelinec** [comment]
@yeekangc I'm working with @proubatsis on this one.

**Comment by AustinSeto** [comment]
Will pull into a development branch for review and updates before merging to site

**Pull request merged**
