### PR TITLE
Remove 'whole' tag, upgrade Liberty Maven Plugin to 2.6.3

### PR DESCRIPTION
**Pull request by chyt**

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
will merge after multipane conversion if still necessary

**Comment by gkwan-ibm** [comment]
@justineechen would you take a look whether we need to remove `[tags=whole]` in multipane?

**Comment by justineechen** [comment]
This is handled by the parent pom update and the [tags=whole] does not affect how the guide looks but can still be removed.

**Comment by gkwan-ibm** [comment]
@chyt Most of the guides are using parent pom. There is no need to generate PRs for updating liberty maven plugin to all the guides, except [the gradle guide](https://github.com/OpenLiberty/guide-gradle-intro). We will let you know if there is other exceptional guide.

**Comment by chyt** [comment]
@gkwan-ibm This is not good practice. Using the `RELEASE` keyword to specify dependency/plugin versions has been deprecated since Maven 2. Please see this issue that I opened: https://github.com/OpenLiberty/guides-common/issues/251

**Comment by gkwan-ibm** [comment]
@chyt we know and understand the issue of using RELEASE. We are willing to change if the solution is good and permanent in our perspective. Would you tell us which version range should be used so that we don't need to update the pom.xml frequently? Not only openliberty-runtime but also feature-bom and liberty-maven-app-parent, etc

**Comment by chyt** [comment]
Moving discussion to https://github.com/OpenLiberty/guides-common/issues/251.

**Pull request closed without merging**
