### PR TITLE
hotspot & name convention update

### PR DESCRIPTION
**Pull request by DannyS03**
https://github.com/OpenLiberty/guides-common/issues/352
https://github.com/OpenLiberty/guides-common/issues/308

### CODE REVIEW

**Comment by DannyS03** [comment]
- Feedback given for wrong guide

**Comment by NimG98** [comment]
This is the correct guide?

**Comment by DannyS03** [comment]
Looks good on qa.

**Comment by DannyS03** [comment]
Looks good on qa.

**Pull request merged**
