### PR TITLE
Change server name to be `defaultServer`

### PR DESCRIPTION
**Pull request by AustinSeto**
Addresses #103 

Replace import of `twyb-intro.adoc` from https://github.com/OpenLiberty/guides-common/ with different statement to match changed server name

### CODE REVIEW

**Review by tt-le — APPROVED** [review]
Looks good in LGDEV.

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
@AustinSeto  need `cd finish` before `mvn liberty:run`

**Comment by AustinSeto** [comment]
Added `cd finish` to address https://github.com/OpenLiberty/guides-common/issues/514

Minor rewording to instruction also made

**Review by tt-le — APPROVED** [review]
LGTM

**Review by gkwan-ibm — APPROVED** [review]

**Pull request merged**
